blog/urls.py
from .models import Article
from django.urls import path
from . import views


app_name = 'articles'
urlpatterns = [
    path('articles/', views.index, name='articles'),
    path('', views.main_page, name='main_page'),
    path('articles/<int:article_id>/', views.article_detail, name='article_detail'),
    path('articles/<int:article_id>/leave_comment', views.leave_comment, name='leave_comment'),
    path('about/', views.about, name='about'),
    path('search/', views.Search.as_view(), name='search'),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/models.py
from django.db import models


class Article(models.Model):
    title = models.CharField('Название', max_length=100)
    content = models.TextField('Содержимое статьи')
    pub_date = models.DateTimeField('Дата публикации', auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'


class Comment(models.Model):
    name = models.CharField('Имя', max_length=100)
    content = models.CharField('Текст комментария', max_length=200)
    pub_date = models.DateTimeField('Дата публикации', auto_now=True)
    art = models.ForeignKey(Article, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

blog/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.core.paginator import Paginator
from django.urls import reverse
from django.views.generic import ListView

from .models import Article


def index(request):
    a = Article.objects.all()
    paginator = Paginator(a, 3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'blog/test.html', {'page_obj': page_obj})


def main_page(request):
    return render(request, 'blog/index.html')


def article_detail(request, article_id):
    a = Article.objects.get(id=article_id)
    comments = a.comment_set.order_by('-pub_date')
    return render(request, 'blog/article_detail.html', {'article': a, 'comments': comments})


def leave_comment(request, article_id):
    a = Article.objects.get(id=article_id)
    a.comment_set.create(name=request.POST['name'], content=request.POST['content'])
    return HttpResponseRedirect(reverse('articles:article_detail', args=(a.id,)))


def about(request):
    return render(request, 'blog/about.html')


# def search_results(request):
#     search = request.POST['search']
#     a = Article.objects.filter(title__icontains=search)
#     paginator = Paginator(a, 3)
#     page_number = request.GET.get('page')
#     page_obj = paginator.get_page(page_number)
#     return render(request, 'blog/search.html', {'page_obj': page_obj})


class Search(ListView):
    paginate_by = 3
    template_name = 'blog/search.html'
    context_object_name = 'articles'

    def get_queryset(self):
        return Article.objects.filter(title__icontains=self.request.GET.get('search'))

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['search'] = self.request.GET.get('search')
        return context

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Главная</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false"
            aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'articles:articles' %}">Статьи</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'articles:about' %}">Обо мне</a>
        </li>
      </ul>
      <form action="{% url 'articles:search' %}" class="d-flex" method="get">
        <input class="form-control me-2" name="search" type="text" placeholder="Найти статью" aria-label="Search">
        <button type="submit" class="btn btn-outline-primary" type="submit">Поиск</button>
      </form>
    </div>
  </div>
</nav>
{% block content %}

{% endblock content %}
</body>
</html>

templates/blog/about.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Обо мне
{% endblock title %}
{% block content %}
<div class="bg-light p-5 m-5 rounded">
    <img src="{% static 'images/papich.jpg' %}" class="img-thumbnail" alt="..."
         width="25%" align="left" hspace="15">
    <h3 align="center">Виталий Папаня</h3>
    <p align="justify">EvilArthas (Папич, Arthas, Величайший) – стример платфортмы Twitch, получивший популярность
        из-за высокого уровня игры, агрессивного, а временами неадекватного поведения и необычного лексикона.</p>
    <p align="justify">
        Настоящее имя Папича – Виталий Цаль (по другим данным – Громяко). В данный момент ему 27 лет,
        проживает в украинском городе Винница. По собственным словам, Виталий не закончил школу, проучивщись
        всего восемь классов. В 2003 году увлёкся игрой в Warcraft III: The Frozen Throne и переключился на
        карту-игровой режим в 2005 году.
    </p>
    <p align="justify">
        Согласно утверждениям, в DotA будущий стример достиг значительных успехов, попав в топ-3
        таблицы лидеров платформы iCCup. С 2007 увлекается игрой в покер, где, по собственным словам,
        удавалось зарабатывать до 300 долларов в месяц. С конца 2012 года, после запуска открытия торговой
        площадки Steam, Виталий подрабатывал перепродажей игровых вещей в DotA 2. Стримить EvilArthas начал
        в 2015 году и до этого как игрок широкой известности не имел.
    </p>
    <p align="justify">
        Виталий называл себя аскетом и говорил, что из дома выходит только в магазин: по его словам,
        такой образ жизни он ведёт с момента, как перестал ходить в школу. Одной из излюбленных тем для
        мемов и шуток его фанатов является предположение, что Виталий никогда не состоял в серьёзных отношениях.
    </p>
    <p align="justify">
        Несколько раз предпринимались попытки деанона стримера с вычислением телефона и адреса,
        но успехом они не увенчались; тем не менее один из подписчиков EvilArthas встретил его в торговом
        центре и записал видео. Фраза «***** ты здоровый», произнесённая в видео, стала локальным мемом.
    </p>
</div>
{% endblock content %}

templates/blog/article_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ article.title }}{% endblock title %}
{% block content %}
<main class="container">
    <div class="bg-light p-5 rounded">
        <h2>{{ article.title }}</h2>
        <br>
        <br>
        <p class="lead">
            {{ article.content }}
        </p>
        <hr>
        <em>Опубликовано: {{ article.pub_date }}</em>
    </div>
    <hr>
    <div class="w-75">
        <h4>Комментарии({{comments.count}})</h4>
        {% if comments %}
            {% for c in comments %}
                <div class="px-5 py-3 border bg-light">
                    <p class="mb-0 fw-bold fs-5">
                        {{ c.name }}
                    </p>
                    <p class="mb-0 fst-italic">
                        {{ c.pub_date }}
                    </p>
                        <br>
                    <p>
                        {{ c.content }}
                    </p>
                </div>
            {% endfor %}
        {% else %}
            <p>
                <div class="p-3 border bg-light">
                    <p class="mb-0 fst-italic align-middle " align="center">
                        No comments yet.
                    </p>
                </div>
            </p>
        {% endif %}
    <br>
    <form action="{% url 'articles:leave_comment' article.id %}" method="post">
        {% csrf_token %}
        <div class="input-group mb-3">
            <input type="text" class="form-control" required placeholder="Имя"
                   name="name" aria-describedby="basic-addon1">
        </div>
        <div class="input-group">
            <textarea class="form-control" required name="content" aria-label="With textarea"></textarea>
        </div>
        <br>
        <button type="submit" class="btn btn-primary">Отправить</button>
    </form>
    </div>
</main>
{% endblock content %}

templates/blog/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Хай гёрлс энд хай зяблс{% endblock title %}
{% block content %}
<div class="px-4 py-5 my-5 text-center">
    <img class="d-block mx-auto mb-4" src="{% static 'images/81TKxGEqVJruMIz7RCN8JA.jpeg' %}" alt="" width="200" height="200">
    <h1 class="display-5 fw-bold">Пам парааааам! Пам парааааааааам!</h1>
    <div class="col-lg-6 mx-auto">
        <p class="lead mb-4">Приветствую смотрящих!</p>
        <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
            <a href="{% url 'articles:articles' %}" class="btn btn-primary btn-lg px-4 gap-3">Статьи</a>
            <a href="{% url 'articles:about' %}" class="btn btn-outline-secondary btn-lg px-4">Обо мне</a>
        </div>
    </div>
</div>
{% endblock content %}

templates/blog/search.html
{% extends 'base.html' %}
{% block title %}
    Статьи
{% endblock title %}
{% block content %}
<main class="container">
{% if articles %}
    {% for a in articles %}
    <div class="bg-light p-5 rounded">
        <h1>{{ a.title }}</h1>
        <em>Опубликовано: {{ a.pub_date }}</em>
        <hr>
        <p class="lead">
            {{ a.content|truncatechars:300 }}
        </p>
        Комментариев: {{ a.comment_set.count }}
        <br>
        <br>
        <a class="btn btn-lg btn-primary" href="{% url 'articles:article_detail' a.id %}" role="button">Читать полностью &raquo;</a>
    </div>
    {% endfor %}
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?search={{ search }}&page=1" aria-disabled="true">First</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?search={{ search }}&page={{ page_obj.previous_page_number }}"
                       aria-disabled="true">{{ page_obj.previous_page_number }}</a>
                </li>
            {% endif %}
            <li class="page-item active" aria-current="page">
                <span class="page-link">{{ page_obj.number }}</span>
            </li>
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?search={{ search }}&page={{ page_obj.next_page_number }}"
                       aria-disabled="true">{{ page_obj.next_page_number }}</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?search={{ search }}&page={{ page_obj.paginator.num_pages }}" aria-disabled="true">Last</a>
                </li>
            {% endif %}
        </ul>
    </nav>
{% else %}
    <h2>Совпадений не найдено</h2>
{% endif %}
</main>
{% endblock content %}

templates/blog/test.html
{% extends 'base.html' %}
{% block title %}
    Статьи
{% endblock title %}
{% block content %}
<main class="container">
    {% for a in page_obj %}
    <div class="bg-light p-5 rounded">
        <h1>{{ a.title }}</h1>
        <em>Опубликовано: {{ a.pub_date }}</em>
        <hr>
        <p class="lead">
            {{ a.content|truncatechars:300 }}
        </p>
        Комментариев: {{ a.comment_set.count }}
        <br>
        <br>
        <a class="btn btn-lg btn-primary" href="{% url 'articles:article_detail' a.id %}" role="button">Читать полностью &raquo;</a>
    </div>
    {% endfor %}
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1" aria-disabled="true">First</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}"
                       aria-disabled="true">{{ page_obj.previous_page_number }}</a>
                </li>
            {% endif %}
            <li class="page-item active" aria-current="page">
                <span class="page-link">{{ page_obj.number }}</span>
            </li>
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}"
                       aria-disabled="true">{{ page_obj.next_page_number }}</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-disabled="true">Last</a>
                </li>
            {% endif %}
        </ul>
    </nav>
</main>
{% endblock content %}